//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contaner
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Configuration;
    using System.Data;

    public partial class EMPLOYEE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string CITY { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<int> DEPTID { get; set; }

        
    }

}
