//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contaner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Configuration;
    using System.Data.SqlClient;
    using System.Data;

    public partial class MVCProjectEntities : DbContext
    {
        public MVCProjectEntities()
            : base("name=MVCProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public void AddEmployee(EMPLOYEE employee)
        {
            string connectionString =
                    ConfigurationManager.ConnectionStrings["MVCProjectEntities"].ConnectionString;

            using (SqlConnection con = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("spAddEmployee", con);
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter paramName = new SqlParameter();
                paramName.ParameterName = "@Name";
                paramName.Value = employee.NAME;
                cmd.Parameters.Add(paramName);

                SqlParameter paramCity = new SqlParameter();
                paramCity.ParameterName = "@city";
                paramCity.Value = employee.CITY;
                cmd.Parameters.Add(paramCity);

                SqlParameter paramAge = new SqlParameter();
                paramAge.ParameterName = "@age";
                paramAge.Value = employee.AGE;
                cmd.Parameters.Add(paramAge);

                SqlParameter paramDId = new SqlParameter();
                paramDId.ParameterName = "@deptid";
                paramDId.Value = employee.DEPTID;
                cmd.Parameters.Add(paramDId);

                con.Open();
                cmd.ExecuteNonQuery();
            }
        }
    }
}
